// EDIT HERE to add a template or update its card, price, category, or colors.
// Keep each id unique. The id is used in template links and saved drafts.
export const templates = [
  {id:'digital-letter',name:'Digital Letter',tag:'ROMANTIC',price:4.99,icon:'💌',theme:'letter',description:'An interactive envelope, a heartfelt letter, and a little flower-filled reveal.',previewTitle:'A note for',starterMessage:'You make ordinary days feel like the best days. I made this little corner of the internet just for you. 💗',colors:['#f4d7dc','#bd7083']},
  {id:'kawaii-letter',name:'Kawaii Digital Letter',tag:'ROMANTIC',price:5.49,icon:'💌',theme:'kawaii',description:'A playful letter with a sealed envelope, cute keepsakes, and animated flowers.',previewTitle:'A tiny note for',starterMessage:'You are my favorite person, my soft place to land, and the cutest part of every day. 🧸',colors:['#f7dce1','#ed94aa']},
  {id:'birthday-bloom',name:'Birthday Bloom',tag:'BIRTHDAY',price:5.99,icon:'🎂',theme:'birthday',description:'Confetti, candles, and a day all about them.',previewTitle:'Today we celebrate',starterMessage:'I hope your birthday brings loud laughs, sweet cake, and everything that makes you feel wonderful. 🎂',colors:['#ffe2a8','#ed8b75']},
  {id:'our-story',name:'Our Story',tag:'ANNIVERSARY',price:5.99,icon:'📖',theme:'scrapbook',description:'A scrapbook for the chapters you share.',previewTitle:'Our story keeps growing',starterMessage:'From our first hello to all the little things since, every chapter with you is my favorite. 📖',colors:['#d9d2b8','#a87860']},
  {id:'little-things',name:'Little Things',tag:'JUST BECAUSE',price:3.99,icon:'🌷',theme:'garden',description:'A soft floral note for an ordinary day.',previewTitle:'For the little things',starterMessage:'Just a reminder that your laugh, your kindness, and the way you show up matter so much. 🌷',colors:['#dce8cf','#78a27c']},
  {id:'starlight',name:'Under the Stars',tag:'ROMANTIC',price:5.99,icon:'🌙',theme:'midnight',description:'A dreamy night sky with a message that shines.',previewTitle:'You are my north star',starterMessage:'Even from far away, you make my whole sky feel brighter. I’m always cheering for you. ✨',colors:['#28335e','#9b8fd0']},
  {id:'polaroid-days',name:'Polaroid Days',tag:'MEMORIES',price:5.49,icon:'📸',theme:'polaroid',description:'Snapshots and captions from your favorite days.',previewTitle:'Snapshots of us',starterMessage:'I keep these moments like little photographs in my heart. Here’s to many more. 📸',colors:['#f8e3b8','#d99b68']},
  {id:'ocean-heart',name:'Ocean Heart',tag:'LONG DISTANCE',price:4.99,icon:'🐚',theme:'ocean',description:'A little wave of love across any distance.',previewTitle:'Across every mile',starterMessage:'No distance could make you feel less close. Sending a little wave of love your way. 🌊',colors:['#b9e0e2','#478b9b']},
  {id:'sunny-side',name:'Sunny Side',tag:'FRIENDSHIP',price:3.99,icon:'☀️',theme:'sunshine',description:'Bright, playful, and made to lift their day.',previewTitle:'A little sunshine',starterMessage:'You have a way of turning an ordinary day into a brighter one. Thanks for being you. ☀️',colors:['#ffdc78','#f39d52']},
  {id:'coffee-date',name:'Coffee Date',tag:'DATE NIGHT',price:4.49,icon:'☕',theme:'coffee',description:'A cozy invitation for your next little adventure.',previewTitle:'Save me a seat',starterMessage:'Coffee tastes better with you. Here’s to another long chat and a little more time together. ☕',colors:['#e5cbb1','#9a6a50']},
  {id:'forever-yours',name:'Forever Yours',tag:'WEDDING',price:6.49,icon:'💍',theme:'classic',description:'An elegant keepsake for a once-in-a-lifetime yes.',previewTitle:'To our forever',starterMessage:'I choose you in every season, in every small moment, and in every tomorrow. 💍',colors:['#e9dfd2','#b69c78']},
  {id:'tiny-dancer',name:'Tiny Dancer',tag:'CELEBRATION',price:5.49,icon:'🪩',theme:'disco',description:'Turn their good news into a bright little party.',previewTitle:'This calls for a dance',starterMessage:'Your good news deserves the biggest celebration. I’m so proud of you—let’s make a night of it! 🪩',colors:['#d9bbef','#8d63b7']},
  {id:'postcard-home',name:'Postcard Home',tag:'TRAVEL',price:4.99,icon:'✈️',theme:'postcard',description:'A postcard-style hello from wherever you are.',previewTitle:'Wish you were here',starterMessage:'A little hello from my corner of the world. Wherever we are, you always feel like home. ✈️',colors:['#b8d9e8','#548ba7']},
  {id:'cozy-corner',name:'Cozy Corner',tag:'THANK YOU',price:3.99,icon:'🧶',theme:'cozy',description:'Warm colors and kind words for someone who shows up.',previewTitle:'A warm thank-you',starterMessage:'You make hard days softer just by being there. I hope this little note gives some of that warmth back. 🧶',colors:['#eac7a3','#bf795b']},
  {id:'wildflower',name:'Wildflower Wishes',tag:'ENCOURAGEMENT',price:4.49,icon:'🌼',theme:'wildflower',description:'A meadow of encouragement, made just for them.',previewTitle:'Keep growing, wildflower',starterMessage:'You don’t need to have it all figured out. You’re doing better than you think, and I believe in you. 🌼',colors:['#e9e2a8','#81a76d']},
  {id:'little-star',name:'Little Star',tag:'NEW BABY',price:5.99,icon:'⭐',theme:'baby',description:'A gentle welcome for the newest love in your life.',previewTitle:'Hello, little star',starterMessage:'The world got brighter the moment you arrived. Wishing your family a lifetime of tiny wonders. ⭐',colors:['#d6e8ee','#96bfd0']},
  {id:'sweet-tooth',name:'Sweet Tooth',tag:'SWEET SURPRISE',price:4.49,icon:'🍓',theme:'berry',description:'A strawberry-sweet treat for your favorite person.',previewTitle:'A berry-sweet note',starterMessage:'Life is sweeter with you around. Consider this your reminder that you’re loved a whole bunch. 🍓',colors:['#ffd5d2','#dc6c79']},
  {id:'music-memo',name:'Our Song',tag:'MUSIC',price:4.99,icon:'🎵',theme:'music',description:'A favorite song, a favorite person, one lovely page.',previewTitle:'Our song, our story',starterMessage:'Every time this song plays, I’m back in that moment with you. Press play and stay awhile. 🎵',colors:['#e9c2d4','#b05e86']},
  {id:'golden-hour',name:'Golden Hour',tag:'APPRECIATION',price:5.49,icon:'🌅',theme:'sunset',description:'A glowing thank-you for someone who makes life brighter.',previewTitle:'You make life glow',starterMessage:'Thank you for bringing so much care and light into the lives around you. This one is for you. 🌅',colors:['#ffcb96','#d6776d']},
  {id:'paw-print',name:'Paw Prints',tag:'PET LOVER',price:4.49,icon:'🐾',theme:'pet',description:'Celebrate the little companion who owns your heart.',previewTitle:'A note for my sidekick',starterMessage:'Thanks for the happy greetings, little adventures, and all the love packed into those paw prints. 🐾',colors:['#d5c6b4','#8e795f']},
  {id:'winter-wishes',name:'Winter Wishes',tag:'HOLIDAY',price:5.49,icon:'❄️',theme:'winter',description:'A warm note wrapped in a little winter wonder.',previewTitle:'A little winter warmth',starterMessage:'Wishing you slow mornings, cozy blankets, and people who make the season feel like home. ❄️',colors:['#d3e4ee','#779bb2']},
  {id:'digital-diary',name:'Digital Diary',tag:'MEMORIES',price:5.99,icon:'📔',theme:'diary',description:'A mixed-media scrapbook with dated memories, captions, and your favorite song.',previewTitle:'Pages from our story',starterMessage:'Some days deserve to be saved. Here are a few pages from the moments I never want to forget. 📔',colors:['#f4d8dc','#c77688']},
];
// SurpriseLink launch offer: every design is free while the service is in preview.
// Keep the regular price so the gallery can show it as a crossed-out reference price.
export const launchPrice = 0;
