import React from 'react';
import { ArrowRight, Check, ShoppingBag } from 'lucide-react';

function GalleryCard({template,inCart,onDetails,onAdd}){return <article className="gallery-card"><button className={`gallery-art art-${template.theme}`} onClick={onDetails} aria-label={`View ${template.name} details`}><span className="gallery-art-label">{template.tag}</span><span className="gallery-art-deco deco-a">{template.icon}</span><span className="gallery-art-deco deco-b">{themeOrnament(template.theme)}</span><span className="gallery-art-title">{template.name}</span><span className="gallery-art-caption">A little something, just for you</span></button><div className="gallery-card-info"><div><h2>{template.name}</h2><p>{template.description}</p></div><span className="gallery-price"><s>${template.price.toFixed(2)}</s><b>$0</b><small>LAUNCH OFFER</small></span></div><div className="gallery-card-actions"><button className="customize-link" onClick={onDetails}>View Details <ArrowRight size={14}/></button><button className="add-cart" onClick={onDetails}>Make it free <ArrowRight size={13}/></button></div></article>}
function themeOrnament(theme){return ({letter:'♡',kawaii:'✿',diary:'❀',birthday:'✦',scrapbook:'✿',garden:'❀',midnight:'✧',polaroid:'✦',ocean:'〰',sunshine:'☼',coffee:'♡',classic:'❦',disco:'✦',postcard:'✈',cozy:'❧',wildflower:'✿',baby:'☾',berry:'♡',music:'♫',sunset:'☼',pet:'🐾',winter:'❄'})[theme]||'♡'}
function EditorDesign({template,gift}){
 const photos=(gift.photos||[]).filter(Boolean).slice(0,3);
 const backgroundStyle=gift.backgroundImage?{backgroundImage:`linear-gradient(180deg,rgba(255,250,247,.58),rgba(255,250,247,.68)),url(${gift.backgroundImage})`,backgroundPosition:'center',backgroundSize:'cover'}:undefined;
 return <div className={`design-preview design-${template.theme} ${photos.length===1?'has-single-photo':''}`} style={backgroundStyle}><div className="design-decoration top-deco">{themeOrnament(template.theme)}　{template.icon}　{themeOrnament(template.theme)}</div><div className="design-art"><span className="design-icon">{template.icon}</span><span className="design-orb orb-one"></span><span className="design-orb orb-two"></span><span className="design-orb orb-three"></span></div>{photos.length===1&&<div className="design-photo-strip single-photo"><img src={photos[0]} alt="Gift memory"/></div>}<span className="design-tag">{template.tag}</span><h2>{template.previewTitle||'A little something for'} <em>{gift.name||'someone special'}</em></h2><div className="design-rule"></div><p>{gift.message||'Your lovely note will appear here.'}</p><span className="design-signature">With love, {gift.from||'you'} ♡</span>{photos.length>1&&<div className="design-photo-strip multi-photo">{photos.map((photo,index)=><img src={photo} alt={`Gift memory ${index+1}`} key={index}/>)}</div>}<div className="design-decoration bottom-deco">{template.name} · made just for you</div></div>
}

export { GalleryCard, themeOrnament, EditorDesign };
